version: 0.0
os: linux
files:
  - source: /
    destination: /var/frontend/
    file_exists_behavior: OVERWRITE

hooks:
  AfterInstall:
    - location: deployments/codeDeploy/scripts/change_permissions.sh
      timeout: 120
      runas: root
